<a href="https://colab.research.google.com/github/WaseemRaza844/Advance-Machine-Learning/blob/master/Copy_of_Set_routines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set routines

In [0]:
import numpy as np

In [0]:
np.__version__

'1.16.4'

In [0]:
author = 'kyubyong. longinglove@nate.com'

## Making proper sets

Q1. Get unique elements and reconstruction indices from x. And reconstruct x.

In [0]:
x = np.array([1, 2, 6, 4, 2, 3, 2])
unique_elements, reconstruction_indices = np.unique(x, return_inverse=True)
print(unique_elements)
print(reconstruction_indices)
reconstructed = unique_elements[reconstruction_indices]
print(reconstructed)

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]


## Boolean operations

Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [0]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])
np.isin(x,y)

array([ True,  True, False, False,  True])

Q3. Find the unique intersection of x and y.

In [0]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
np.intersect1d(x,y)

array([0, 1])

Q4. Find the unique elements of x that are not present in y.

In [0]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
np.setdiff1d(x,y)

array([2, 5])

Q5. Find the xor elements of x and y.

In [0]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.setxor1d(x, y)
print(out1)
out2 = np.sort(np.concatenate((np.setdiff1d(x, y), np.setdiff1d(y, x))))
print(out2)
assert np.allclose(out1, out2)

[2 4 5]
[2 4 5]


Q6. Find the union of x and y.

In [0]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.union1d(x, y)
print(out1)
out2 = np.sort(np.unique(np.concatenate((x, y))))
print(out2)
assert np.allclose(out1, out2)

[0 1 2 4 5]
[0 1 2 4 5]
