<a href="https://colab.research.google.com/github/WaseemRaza844/Advance-Machine-Learning/blob/master/Copy_of_Random_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Sampling

In [0]:
import numpy as np

In [0]:
np.__version__

'1.16.4'

In [0]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [0]:
s = np.random.uniform(0,1,6).reshape(3,2)
print(s)

[[0.88021974 0.03308379]
 [0.74333035 0.58933284]
 [0.17798499 0.3618248 ]]


Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [0]:
s = np.random.standard_normal(size=(1000,1000))
print(np.mean(s))
print(np.std(s))

-9.668039948776327e-05
1.0007880476447468


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [0]:
np.random.randint(0,4, size=(3,2))

array([[1, 3],
       [1, 3],
       [1, 2]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [0]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
print(x)
print(b)

['3 out of 10', '5 out of 10', '2 out of 10']


NameError: ignored

Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [0]:
data=np.arange(0,10)
np.random.choice(data,3)

array([4, 7, 2])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [0]:
data=np.arange(0,10)
np.random.shuffle(data)
data

array([3, 7, 4, 6, 8, 2, 1, 5, 0, 9])

In [0]:
# Or


[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [0]:
np.random.seed(10) 
print np.random.rand(4)
np.random.seed(10) 
print np.random.rand(4)

[0.77132064 0.02075195 0.63364823 0.74880388]
[0.77132064 0.02075195 0.63364823 0.74880388]
